config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'

  resources :habits, only: :show do
    member do
      post :increment
      post :decrement
    end
  end

  resources :tasks do
    post :toggle, on: :member, defaults: { format: :json }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/habit.rb
class Habit < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  before_action :set_habit

  def show; end

  def increment
    @habit.update(count: @habit.count + 1)
    redirect_to @habit
  end

  def decrement
    @habit.update(count: @habit.count - 1)
    redirect_to @habit
  end

  private

  def set_habit
    @habit = Habit.find(params['id'])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_url, notice: 'Task was successfully updated' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path, notice: 'Task was successfully created.' }
      else
        format.html { render :index }
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def toggle
    @task = Task.find(params[:id])
    @task.update(completed: params[:completed])

    render json: { message: 'Success' }
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_url, notice: 'Task was successfully destroyed.'
  end

  private

  def task_params
    params.require(:task).permit(:description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/habits_helper.rb
module HabitsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/habits/show.html.erb
<section class="mx-auto mt-28 w-96 p-5 border rounded">
  <div class="text-center font-bold text-gray-700" id="habit-name">
    <%= @habit.name %>
  </div>

  <div class="mt-3 flex justify-center items-center space-x-5">
    <%= button_to "-", decrement_habit_path(@habit), class: "btn bg-red-300 inline-block shadow-lg" %>
    <div class="text-4xl font-bold"><%= @habit.count %></div>
    <%= button_to "+", increment_habit_path(@habit), class: "btn bg-green-300 inline-block shadow-lg" %>
  </div>

  <div class="mt-3 p-2 flex justify-center space-x-1">
    <% @habit.count.times do %>
      <div class="inline-block border p-1 bg-green-400"></div>
    <% end %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hotdo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, class: "mb-7") do |form| %>
  <div class="mb-5">
    <%= form.text_field :description, placeholder: "Add new task", class: "inline-block w-96 px-3 py-2 mt-2 shadow rounded-md border border-gray-200 outline-none" %>
    <%= form.submit "Save", class: "btn py-2 ml-2 bg-blue-600 text-white" %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<turbo-frame id="<%= dom_id(task) %>" class="block">
  <%= form_with(model: task, class:"text-lg inline-block my-3 w-72") do |form| %>
    <%= form.check_box :completed,
                      data: {
                        id: task.id,
                        action: "tasks#toggle"
                      },
                      class: "mr-2 align-middle bg-gray-50 border-gray-300 focus:ring-3 focus:ring-blue-300 h-5 w-5 rounded checked:bg-green-500" %>
    <%= task.description %>
  <% end %>

  <%= link_to "Edit", edit_task_path(task), class: "btn bg-gray-100" %>

  <div class="inline-block ml-2">
    <%= button_to "Delete", task_path(task),
                  method: :delete,
                  data: { "turbo-frame": "_top" },
                  class: "btn bg-red-100" %>
  </div>
</turbo-frame>

app/views/tasks/edit.html.erb
<div>
  <h1 class="font-bold text-2xl mb-3">Editing Task</h1>

  <turbo-frame id="<%= dom_id(@task) %>" class="block">
    <%= render "form", task: @task %>
    <%= link_to "Never Mind", tasks_path, class: "btn mb-3 bg-gray-100" %>
  </turbo-frame>
</div>

app/views/tasks/index.html.erb
<% if notice.present?  %>
  <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice">
    <%= notice %>
  </p>
<% end %>

<h1 class="font-bold text-2xl">Task Manager</h1>

<div class="mt-4">
  <%= render "form", task: @task %>
</div>

<div id="tasks">
  <h1 class="font-bold text-lg mb-7">Tasks</h1>

  <div class="px-5" data-controller="tasks">
    <%= render @tasks %>
  </div>
</div>

<%= form_for(@task, url: tasks_path) do |f| %>
  <div class='form-group'>
    <%= f.select :id, Task.all.collect { |tsk| [tsk.description, tsk.id] }, {}, { value: @task.id, class: 'form-control', onchange: 'this.form.submit();' } %>
  </div>
<% end %>